version: '2'
services:
  wordpress:
    image: visiblevc/wordpress:latest
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./data:/data
      - ./zorbixthemes:/app/wp-content/themes/zorbixthemes
      - ./zorbix-framework-dev/zorbix-framework2:/app/wp-content/plugins/zorbix-framework2
      - ./themes-showcase:/app/wp-content/plugins/themes-showcase
      - ./knowledgebase:/app/wp-content/plugins/knowledgebase
    environment:
      DB_NAME: wordpress
      DB_PASS: root
      THEMES: >-
        [local]zorbixthemes
      PLUGINS: >-
        query-monitor,
        wpcore,
        [local]wp-migrate-db-pro.zip,
        [local]zorbix-framework,
        [local]themes-showcase,
        [local]knowledgebase,
  db:
    image: mariadb:10 # or mysql:5.7
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
        MYSQL_ROOT_PASSWORD: root
      ports:
        - 22222:80
volumes:
  data: